import { tokens } from "./tokens";

const HEADER =
  "/* GENERATED by packages/ui/scripts/generate-theme.ts from src/tokens.ts. Do not edit by hand. */";

/**
 * Renders the Tailwind v4 theme from the design tokens, so `tokens.ts` stays the only place
 * a color, font, or radius is defined. Run `pnpm --filter @forgely/ui generate:theme` after
 * changing tokens; a test fails if the committed file is out of date.
 *
 * Color names avoid Tailwind's own utility words (`text-base` is a font size, so the base
 * surface is called `surface`).
 */
export function renderThemeCss(): string {
  const { color, radius, motion } = tokens;

  const colors: Record<string, string> = {
    surface: color.surface.base,
    "surface-raised": color.surface.raised,
    "surface-overlay": color.surface.overlay,
    "surface-inset": color.surface.inset,
    line: color.border.subtle,
    "line-strong": color.border.strong,
    fg: color.text.primary,
    muted: color.text.secondary,
    ink: color.text.onEmber,
    bone: color.bone,
    "ember-400": color.ember[400],
    ember: color.ember[500],
    "ember-600": color.ember[600],
    "ember-700": color.ember[700],
    success: color.status.success,
    warning: color.status.warning,
    danger: color.status.danger,
    dot: color.dot,
  };

  const theme = [
    ...Object.entries(colors).map(([name, value]) => `  --color-${name}: ${value};`),
    ...Object.entries(radius)
      .filter(([name]) => name !== "full")
      .map(([name, value]) => `  --radius-${name}: ${value}px;`),
    `  --ease-forge: ${motion.easing};`,
  ];

  // Fonts reference the CSS variables that next/font creates, so they need `inline`.
  const fonts = [
    `  --font-display: var(--font-archivo), ${tokens.font.display};`,
    `  --font-sans: var(--font-hanken), ${tokens.font.body};`,
    `  --font-mono: var(--font-jetbrains), ${tokens.font.mono};`,
  ];

  return [HEADER, "@theme {", ...theme, "}", "", "@theme inline {", ...fonts, "}", ""].join("\n");
}
